name: Find Adjacent Repositories

on:
  schedule:
    - cron: '0 5 * * 0'   # Every Sunday at 5am UTC
  workflow_dispatch:

jobs:
  recommend-repos:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing commits
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Adjacent Repositories Recommender
        uses: gojiplus/adjacent@v1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ Pass the required token

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update adjacent repositories [automated]"
            git push
          fi